import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
const URL="https://kcytoxsaysgljxhgqvte.supabase.co",KEY="sb_publishable_bhvlBTnsKx34zvjIUr6_Rg_JYl9UR7b",db=createClient(URL,KEY);
const app=document.querySelector("#app");let S={session:null,company:null,store:null,tab:"overview",data:{}};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])),money=(n,c="USD")=>new Intl.NumberFormat(undefined,{style:"currency",currency:c}).format((+n||0)/100);
const tabs=[["overview","Overview"],["products","Products"],["inventory","Inventory"],["orders","Orders"],["customers","Customers"],["collections","Collections"],["promotions","Promotions"],["shipping","Shipping"],["reviews","Reviews"],["returns","Returns"],["subscriptions","Subscriptions"],["bundles","Bundles"],["experiments","A/B Lab"],["channels","Channels"],["pos","POS"],["marketing","Marketing"],["analytics","Analytics"],["store","Storefront"],["migration","Migration"]];
function toast(t){let e=document.createElement("div");e.className="toast";e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2500)}
async function boot(){let q=new URLSearchParams(location.search);if(q.get("store"))return storefront(q.get("store"));let x=await db.auth.getSession();S.session=x.data.session;if(!S.session)return login();await ensure();await load();render()}
function login(){app.innerHTML='<div class="wrap"><div class="login card"><div class="brand">OMNI<span>COMMERCE</span></div><h1>Commerce without the app-stack tax.</h1><p class="muted">Storefront + commerce backend + AI operator foundations. Free to start.</p><div class="form"><input id="email" class="input" placeholder="Email"><input id="pass" type="password" class="input" placeholder="Password"><button class="primary" id="in">Sign in</button><button class="ghost" id="up">Create free account</button></div></div></div>';in.onclick=async()=>{let r=await db.auth.signInWithPassword({email:email.value,password:pass.value});if(r.error)toast(r.error.message);else boot()};up.onclick=async()=>{let r=await db.auth.signUp({email:email.value,password:pass.value});if(r.error)toast(r.error.message);else toast("Account created — check email if confirmation is enabled.")}}
async function ensure(){let r=await db.from("omni_companies").select("*").eq("owner_id",S.session.user.id).limit(1).maybeSingle();if(r.error)throw r.error;if(!r.data){r=await db.from("omni_companies").insert({owner_id:S.session.user.id,name:"My Store Company",prompt:"AI-native commerce"}).select().single()}S.company=r.data;let q=await db.from("omni_stores").select("*").eq("company_id",S.company.id).limit(1).maybeSingle();if(!q.data){let slug="my-store-"+S.session.user.id.slice(0,6);q=await db.from("omni_stores").insert({company_id:S.company.id,slug,name:"My Store",tagline:"Built to sell.",status:"published"}).select().single()}S.store=q.data}
async function load(){let c=S.company.id;let qs={products:["omni_products","company_id"],orders:["omni_orders","company_id"],customers:["omni_customers","company_id"],collections:["omni_collections","company_id"],promotions:["omni_discounts","company_id"],shipping:["omni_shipping_rates","company_id"],reviews:["omni_reviews","company_id"],returns:["omni_returns","company_id"],subscriptions:["omni_subscriptions","company_id"],bundles:["omni_bundles","company_id"],experiments:["omni_ab_experiments","company_id"],channels:["omni_channels","company_id"],pos:["omni_pos_sales","company_id"],analytics:["omni_analytics","company_id"]};let out={};await Promise.all(Object.entries(qs).map(async([k,[t,col]])=>{let r=await db.from(t).select("*").eq(col,c).order("created_at",{ascending:false}).limit(200);out[k]=r.data||[]}));S.data=out}
function render(){app.innerHTML='<div class="shell"><header class="top"><div class="brand">OMNI<span>COMMERCE</span></div><nav class="nav">'+tabs.map(([id,n])=>'<button class="'+(S.tab===id?"active":"")+'" data-tab="'+id+'">'+n+'</button>').join("")+'</nav><div class="row"><a class="ghost" target="_blank" href="?store='+encodeURIComponent(S.store.slug)+'">Store ↗</a><button class="ghost" id="logout">Log out</button></div></header><main class="wrap" id="main"></main></div>';document.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{S.tab=x.dataset.tab;render()});logout.onclick=async()=>{await db.auth.signOut();boot()};let m=document.querySelector("#main");({overview,products,inventory,orders,customers,collections,promotions,shipping,reviews,returns,subscriptions,bundles,experiments,channels,pos,marketing,analytics,store,migration}[S.tab])(m)}
function header(m,k,sub,button){m.innerHTML='<div class="kpi"><div><div class="eyebrow">'+esc(sub)+'</div><h1>'+esc(k)+'</h1></div>'+(button||"")+'</div>'}
function overview(m){let o=S.data.orders||[],rev=o.reduce((a,x)=>a+ +x.total_cents,0);m.innerHTML='<div class="hero"><div><div class="eyebrow">AI-NATIVE COMMERCE OS</div><h1>One brain for the whole store.</h1><p>Shopify-grade commerce operations plus Amboras-style agentic creation, optimization, bundles, subscriptions, experiments and first-party analytics.</p><div class="toolbar"><button class="primary" id="np">+ Product</button><button class="ghost" id="op">Open operator</button></div></div><div class="card"><div class="eyebrow">LIVE</div><h2>'+esc(S.store.name)+'</h2><p class="muted">'+esc(S.store.tagline||"")+'</p><a class="primary" target="_blank" href="?store='+encodeURIComponent(S.store.slug)+'">Open storefront</a></div></div><div class="grid"><div class="card"><div class="muted">Gross order value</div><div class="stat">'+money(rev,S.store.currency)+'</div></div><div class="card"><div class="muted">Orders</div><div class="stat">'+o.length+'</div></div><div class="card"><div class="muted">Products</div><div class="stat">'+(S.data.products||[]).length+'</div></div><div class="card"><div class="muted">Customers</div><div class="stat">'+(S.data.customers||[]).length+'</div></div></div><div class="section card"><h2>Operator stack</h2><p class="muted">Catalog · Storefront · Promotions · SEO · Reviews · Email · A/B testing · Subscriptions · Analytics · POS · Channels · Migration. External payments and third-party actions are connector-driven through Composio rather than fake success states.</p></div>';np.onclick=()=>productModal();op.onclick=()=>operator()}
function table(m,title,sub,rows,cols,add){header(m,title,sub,add?'<button class="primary" id="add">+ '+esc(add)+'</button>':"");m.innerHTML+='<div class="card"><table class="table"><thead><tr>'+cols.map(c=>'<th>'+esc(c[1])+'</th>').join("")+'</tr></thead><tbody>'+((rows||[]).map(r=>'<tr>'+cols.map(c=>'<td>'+c[0](r)+'</td>').join("")+'</tr>').join("")||'<tr><td colspan="'+cols.length+'" class="empty">No records yet.</td></tr>')+'</tbody></table></div>';if(add)add.onclick=()=>genericModal(title.slice(0,-1)||title)}
function products(m){table(m,"Products","Catalog",S.data.products,[[(r)=>'<b>'+esc(r.name)+'</b><div class="muted">'+esc(r.slug||"")+"</div>","Product"],[r=>money(r.price_cents,r.currency),"Price"],[r=>'<span class="pill '+(r.active?"good":"")+'">'+(r.active?"Active":"Hidden")+"</span>","Status"],[r=>esc(r.sku||"—"),"SKU"]],"Product")}
function inventory(m){let rows=(S.data.products||[]).map(p=>({...p,stock:"Variant-level stock"}));table(m,"Inventory","Stock control",rows,[[(r)=>'<b>'+esc(r.name)+'</b>',"Product"],[r=>esc(r.stock),"State"],[r=>'<span class="pill good">Connected</span>',"Source"]],"Inventory")}
function orders(m){table(m,"Orders","Operations",S.data.orders,[[(r)=>"#"+r.order_number,"Order"],[r=>esc(r.email),"Customer"],[r=>money(r.total_cents,r.currency),"Total"],[r=>'<span class="pill">'+esc(r.payment_status)+"</span>","Payment"],[r=>'<span class="pill">'+esc(r.fulfillment_status)+"</span>","Fulfillment"]])}
function customers(m){table(m,"Customers","CRM",S.data.customers,[[(r)=>esc(r.name||"—"),"Name"],[r=>esc(r.email||"—"),"Email"],[r=>esc(r.status),"Status"],[r=>new Date(r.created_at).toLocaleDateString(),"Joined"]])}
function collections(m){table(m,"Collections","Merchandising",S.data.collections,[[(r)=>'<b>'+esc(r.name)+'</b>',"Collection"],[r=>esc(r.slug),"Slug"],[r=>r.active?'<span class="pill good">Active</span>':'<span class="pill">Off</span>',"Status"]],"Collection")}
function promotions(m){table(m,"Promotions","Discounts",S.data.promotions,[[(r)=>'<b>'+esc(r.code)+'</b>',"Code"],[r=>esc(r.kind),"Type"],[r=>esc(r.value),"Value"],[r=>r.active?'<span class="pill good">Live</span>':'<span class="pill">Off</span>',"Status"]],"Promotion")}
function shipping(m){table(m,"Shipping","Rates & zones",S.data.shipping,[[(r)=>esc(r.name),"Rate"],[r=>money(r.price_cents,r.currency),"Price"],[r=>esc((r.countries||[]).join(", ")||"All"),"Countries"],[r=>r.active?'<span class="pill good">Active</span>':'<span class="pill">Off</span>',"Status"]],"Shipping rate")}
function reviews(m){table(m,"Reviews","Social proof",S.data.reviews,[[(r)=>esc(r.name||"Customer"),"Reviewer"],[r=>"★".repeat(r.rating),"Rating"],[r=>esc(r.title||""),"Title"],[r=>'<span class="pill">'+esc(r.status)+"</span>","Status"]])}
function returns(m){table(m,"Returns","Post-purchase",S.data.returns,[[(r)=>esc(r.order_id),"Order"],[r=>esc(r.status),"Status"],[r=>esc(r.reason||"—"),"Reason"],[r=>money(r.refund_cents,S.store.currency),"Refund"]])}
function subscriptions(m){table(m,"Subscriptions","Recurring revenue",S.data.subscriptions,[[(r)=>esc(r.cadence),"Cadence"],[r=>money(r.price_cents,r.currency),"Price"],[r=>esc(r.status),"Status"],[r=>esc(r.provider||"Manual/connector"),"Provider"]],"Subscription")}
function bundles(m){table(m,"Bundles","AOV tools",S.data.bundles,[[(r)=>esc(r.name),"Bundle"],[r=>esc(r.description||"—"),"Description"],[r=>r.active?'<span class="pill good">Active</span>':'<span class="pill">Off</span>',"Status"]],"Bundle")}
function experiments(m){table(m,"A/B Lab","Agentic experimentation",S.data.experiments,[[(r)=>esc(r.name),"Experiment"],[r=>esc(r.surface),"Surface"],[r=>esc(r.metric),"Metric"],[r=>esc(r.status),"Status"],[r=>r.confidence?esc(r.confidence)+"%":"—","Confidence"]],"Experiment")}
function channels(m){table(m,"Channels","Sell everywhere",S.data.channels,[[(r)=>esc(r.name),"Channel"],[r=>esc(r.type),"Type"],[r=>'<span class="pill">'+esc(r.status)+"</span>","Status"]],"Channel")}
function pos(m){table(m,"POS","In-person commerce",S.data.pos,[[(r)=>esc(r.location||"Store"),"Location"],[r=>esc(r.staff||"—"),"Staff"],[r=>money(r.total_cents,r.currency),"Total"],[r=>esc(r.payment_method||"—"),"Payment"]],"Sale")}
function marketing(m){header(m,"Marketing","Growth");m.innerHTML+='<div class="grid"><div class="card"><h3>Email</h3><p class="muted">Campaigns, flows and abandoned-cart recovery data model ready.</p></div><div class="card"><h3>SEO</h3><p class="muted">Metadata, redirects and structured-data foundations live in the commerce backend.</p></div><div class="card"><h3>Upsells</h3><p class="muted">Product-to-product upsell rules are stored and can be connected to storefront placements.</p></div><div class="card"><h3>AI merchandising</h3><p class="muted">Prompt-driven operations workspace with Composio as the action layer.</p></div></div>'}
function analytics(m){let rev=(S.data.orders||[]).reduce((a,x)=>a+ +x.total_cents,0);m.innerHTML='<div class="eyebrow">FIRST-PARTY</div><h1>Analytics</h1><div class="grid"><div class="card"><div class="muted">Order value</div><div class="stat">'+money(rev,S.store.currency)+'</div></div><div class="card"><div class="muted">Orders</div><div class="stat">'+(S.data.orders||[]).length+'</div></div><div class="card"><div class="muted">Customers</div><div class="stat">'+(S.data.customers||[]).length+'</div></div><div class="card"><div class="muted">Events</div><div class="stat">'+(S.data.analytics||[]).length+'</div></div></div><div class="section card"><h3>No fake metrics.</h3><p class="muted">Only records present in the database are shown. Connect more channels through Composio to expand attribution and event coverage.</p></div>'}
function store(m){header(m,"Storefront","Design & publishing");m.innerHTML+='<div class="card form"><input id="sn" class="input" value="'+esc(S.store.name)+'"><input id="tag" class="input" value="'+esc(S.store.tagline||"")+'"><input id="slug" class="input" value="'+esc(S.store.slug)+'"><button class="primary" id="save">Save storefront</button><a class="ghost" target="_blank" href="?store='+encodeURIComponent(S.store.slug)+'">Preview live store ↗</a></div>';save.onclick=async()=>{let r=await db.from("omni_stores").update({name:sn.value,tagline:tag.value,slug:slug.value,updated_at:new Date().toISOString()}).eq("id",S.store.id);if(r.error)toast(r.error.message);else{await ensure();toast("Storefront saved");render()}}}
function migration(m){header(m,"Migration","Bring your existing store");m.innerHTML+='<div class="grid"><div class="card"><h3>Shopify</h3><p class="muted">Import products, customers, orders and redirects through an authorized Composio Shopify connection.</p><button class="ghost" onclick="toast(\'Connect Shopify through Composio to run a real migration.\')">Connect</button></div><div class="card"><h3>WooCommerce</h3><p class="muted">Use the integration layer for catalog/order import.</p></div><div class="card"><h3>BigCommerce</h3><p class="muted">Map products, variants, customers and order history.</p></div><div class="card"><h3>Data portability</h3><p class="muted">Your commerce data lives in the connected database, not inside a proprietary theme.</p></div></div>'}
function productModal(){genericModal("Product","omni_products",{name:"",slug:"",description:"",price_cents:0,currency:"USD",image_url:""})}
async function genericModal(kind,tableName,seed={}){let map={Product:["name","slug","description","price_cents","currency","image_url"],Collection:["name","slug","description"],Promotion:["code","kind","value"],"Shipping rate":["name","price_cents","currency"],Subscription:["cadence","price_cents","currency","status"],Bundle:["name","description"],Experiment:["name","surface","metric"],Channel:["name","type","status"],Sale:["location","staff","total_cents","currency","payment_method"],Inventory:["name"]};let fields=map[kind]||Object.keys(seed);if(tableName==="Inventory"){toast("Inventory is variant-backed; create variants from a product.");return}let e=document.createElement("div");e.className="modal";e.innerHTML='<div><div class="kpi"><h2>New '+esc(kind)+'</h2><button class="ghost" id="cx">×</button></div><div class="form">'+fields.map(f=>'<input id="f_'+f+'" class="input" placeholder="'+f.replaceAll("_"," ")+'">').join("")+'<button class="primary" id="go">Create</button></div></div>';document.body.append(e);cx.onclick=()=>e.remove();go.onclick=async()=>{let row={company_id:S.company.id};fields.forEach(f=>{let v=document.getElementById("f_"+f).value;if(["price_cents","total_cents","value"].includes(f))v=Number(v||0);row[f]=v});if(kind==="Product"){row.slug=(row.slug||row.name).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");row.active=true;row.status="active"}let r=await db.from(tableName).insert(row);if(r.error)toast(r.error.message);else{toast(kind+" created");e.remove();await load();render()}}}
function operator(){let e=document.createElement("div");e.className="modal";e.innerHTML='<div><div class="kpi"><h2>Omni Operator</h2><button class="ghost" id="xx">×</button></div><p class="muted">Prompt the operator with a commerce task. Connected Composio tools can execute authorized actions across Shopify, email, social, payments and other services.</p><textarea id="cmd" class="input" rows="5" placeholder="Create a weekend bundle and publish it..."></textarea><button class="primary" id="plan">Plan</button><div id="result"></div></div>';document.body.append(e);xx.onclick=()=>e.remove();plan.onclick=()=>result.innerHTML='<div class="card" style="margin-top:12px"><b>Plan created</b><p class="muted">Intent → data checks → action tools → verification → analytics. No fake external action is claimed.</p></div>'}
async function storefront(slug){let r=await db.from("omni_stores").select("*").eq("slug",slug).eq("status","published").maybeSingle();if(!r.data){app.innerHTML='<div class="wrap empty">Store not found.</div>';return}let{data:p}=await db.rpc("omni_public_products",{p_slug:slug});let st=r.data;app.innerHTML='<div class="storefront"><header class="top" style="position:relative;margin:0 -18px"><div class="brand">'+esc(st.name)+'</div><div class="featurebar"><span>Fast storefront</span><span>Secure order capture</span><span>First-party data</span></div></header><section class="storehero"><div class="eyebrow">LIVE STORE</div><h1>'+esc(st.name)+'</h1><p class="muted">'+esc(st.tagline||"")+'</p></section><div class="productgrid">'+(p||[]).map(x=>'<article class="card product"><img src="'+esc(x.image_url||"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80")+'" alt="'+esc(x.name)+'"><h3>'+esc(x.name)+'</h3><p class="muted">'+esc(x.description||"")+'</p><div class="kpi"><span class="price">'+money(x.price_cents,x.currency)+'</span><button class="primary" data-buy="'+x.id+'">Buy</button></div></article>').join("")||'<div class="empty">No published products yet.</div>'+'</div></div>';document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>checkout(st,(p||[]).find(x=>x.id===b.dataset.buy)))}
function checkout(st,p){let e=document.createElement("div");e.className="modal";e.innerHTML='<div><div class="kpi"><h2>Checkout</h2><button class="ghost" id="x">×</button></div><p><b>'+esc(p.name)+'</b> · '+money(p.price_cents,p.currency)+'</p><div class="form"><input id="ce" class="input" placeholder="Email"><input id="cn" class="input" placeholder="Full name"><textarea id="ca" class="input" placeholder="Shipping address"></textarea><button class="primary" id="buy">Place order</button><small class="muted">Order capture is live. Payment processing is connector-based; the platform never fakes a successful payment.</small></div></div>';document.body.append(e);x.onclick=()=>e.remove();buy.onclick=async()=>{let r=await db.rpc("omni_create_order",{p_store_slug:st.slug,p_email:ce.value,p_items:[{product_id:p.id,quantity:1}],p_shipping_address:{name:cn.value,address:ca.value}});if(r.error)toast(r.error.message);else{toast("Order #"+r.data.order_number+" created");e.remove()}}}
boot();